export const APP_CONFIG = {
  GAMIFICATION: {
    XP_PER_CORRECT_ANSWER: 10,
    XP_COMPLETION_BONUS: 5,
    XP_PER_LEVEL: 100,
  },
  QUIZ: {
    TIME_WINDOW_START: 7,
    TIME_WINDOW_END: 9,
  },
  API: {
    YANDEX_GPT_TIMEOUT: 45000,
    SPEECHKIT_POLLING_INTERVAL: 5000,
    SPEECHKIT_FETCH_TIMEOUT: 15000,
    YOUTUBE_FETCH_TIMEOUT: 3000,
  },
} as const;
